### PR TITLE
update to use modern ruby

### PR DESCRIPTION
**Pull request by marcinruszkiewicz**
This PR brings back this gem to life. It will continue to work on current Ruby versions pretty much unchanged. There are some minor drawbacks, but I think they are acceptable.

Changes included:
- updated versions of dependencies to allow modern Ruby versions
- switched Slop in favor of Thor
- removed some pointless files from the dummy version of Rails used for the tests
- added Appraisal gem to enable testing on different Rails version and make the maintenance of the dummy Rails above much easier
- updated Travis config to include still supported Ruby versions (and 2.3 which is not supported anymore but recent enough)

Drawbacks:
- Lost ability to do `zapata app/models/model.rb`, you need to always do `zapata generate app/models/model.rb`. 

This happened because Thor doesn't support default arguments, and Thor was used because the newest version of Slop stopped supporting commands for whatever reason. I've decided to leave it that way, because I think it's still acceptable.

- I had to change one test, the hash one - `expect(test_hash.test_keys_are_symbols({ this: 'should', be: 'pretty' })).to eq({ be: 'pretty', this: 'should' })`. 

Apparently new Ruby versions will sort the hash keys by default, because no library code was changed to break this. As above, I think it's acceptable and not a big deal - the idea behind that test and code seemed to be focused more on making sure the keys are properly formatted symbols, which obviously is still happening. 

All of this is of course passing all the tests that were there: https://travis-ci.com/marcinruszkiewicz/zapata/builds/130139872

### CODE REVIEW

**Comment by jjensn** [comment]
Thanks for your work on this

**Comment by Nedomas** [comment]
@marcinruszkiewicz This looks great and I'm stoked to see this running again. Pardon for slow response. I'll debug this over the next few days and potentially merge + release this. Thanks!

**Comment by marcinruszkiewicz** [comment]
Sure thing, you do it when you have time :)

**Comment by Nedomas** [comment]
Pardon for such a long delay @marcinruszkiewicz . I've just ran the whole suite on the update here and it works perfectly. Me and @jpalumickas will just fix a few quirks and release a new version.

Thanks!

**Pull request merged**
